import pytest


if __name__=="__main__":
    pytest.main(["--alluredir=report","-s",\
                 "-m" ,\
                 # "login_phone or "
                 # "login_sms"
                 # "weixin_login"
                 # "login_third or "
                 # "register or "
                 "register_third"
                 # "register_enterprise or"
                 # "change_nickname or "
                 # "change_email_or_password or "
                 # "change_mobilephone or "
                 # "change_viptype"
                 # "check_email"
                 # "check_mobilephone or "
                 # "check_sms_vcode"
                 # "check_email_vcode or "
                 # "mobile_bind_status"
                 # "get_user_info or "
                 # "get_user_info_by_email_or_nickname"
                 # "get_user_info_by_mobilephone or "
                 # "get_encrypted_custid or "
                 # "get_custid_by_encrypted_custid or "
                 # "get_user_viptype or "
                 # "weixin_bind_status"
                 # "weixin_get_bind_list"
                 # "weixin_register or "
                 #  "weixin_bind_custid or "
                 # "weixin_unbind_delete or "
                 # "weixin_get_openid"
                 # "weixin_set_openid"
                 # "weixin_unbind"
                 # "get_combine_relation"
                 # "combinestatus"
                 # "getuserprofile"
                 # "combine"
                 #"setuserprofile"
                 #"changeprofileimg"
                 #"setcompanyprofileallinfo"
                 #"setuserprofileallinfo"
                 # "send_email_vcode"
                 # "send_sms_vcode"
                 # "weixinverify"
                 # "getweixinbindcustid"
                 # "combineverify"
                 # "getcombineresult"
                 # "setcombineresult"
                 # "third_register_bind or "
                 # "find_custid_from_sharesignlink or "
                 #"find_bind_third_user"
                 ])